---
# Applies the whole application stack to all nodes

- name: apply common configuration to all nodes
  hosts: all
  roles:
    - common

- name: configure the webservers
  hosts: webservers
  roles:
    - web
