---
# These tasks install nginx

- name: Install nginx
  become: yes
  yum: name=nginx state=present

- name: Enable nginx service
  become: yes
  service: name=nginx state=started enabled=yes

- name: Add nginx sites-enabled/available folders
  become: yes
  file: path=/etc/nginx/{{ item }} state=directory owner=root group=root mode=0755
  with_items:
    - sites-enabled
    - sites-available

- name: Create deployment directory
  become: yes
  file: dest=/var/www/lighthousedemo state=directory owner=nginx group=nginx

- name: Copy nginx Configuration
  become: yes
  template: src=lighthousedemo.ca.conf.j2 dest=/etc/nginx/sites-available/lighthousedemo.ca.conf owner=root group=root
  notify: restart nginx

- name: Symlink nginx configuration
  become: yes
  file:
    src: '/etc/nginx/sites-available/lighthousedemo.ca.conf'
    dest: '/etc/nginx/sites-enabled/lighthousedemo.ca.conf'
    state: link
  notify: restart nginx

- name: Create certificates directory
  become: yes
  file:
    dest: /etc/nginx/certificates
    state: directory

- name: Copy certificates
  become: yes
  copy:
    dest: '/etc/nginx/certificates/{{ item }}'
    src: '{{ item }}'
    owner: root
    group: root
  notify: restart nginx
  with_items:
    - lighthouse.key
    - lighthouse.crt

- name: Configure nginx
  become: yes
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  notify: restart nginx

- name: Copy over html file
  become: yes
  file: src=index.html dest=/var/www/lighthousedemo/index.html owner=nginx group=nginx
