---
# This playbook contains common plays that will be run on all nodes

- name: Install EPEL
  sudo: yes
  yum: name=epel-release state=present

- name: Install NTP
  sudo: yes
  yum: name=ntp state=present
  tags: ntp

- name: Setup Timezone
  sudo: yes
  command: timedatectl set-timezone America/Toronto
  tags: ntp
  notify: restart ntp

- name: Start the ntp service
  sudo: yes
  service: name=ntpd state=started enabled=yes
  tags: ntp
